---
apiVersion: v1
kind: Service
metadata:
  name: argocd-service-port
  namespace: argocd
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: argocd-server

## kubectl -n argocd -f argocd-service.yaml apply
