# Git repositories configure Argo CD with (optional).
# This list is updated when configuring/removing repos from the UI/CLI
# Note: the last example in the list would use a repository credential template, configured under "argocd-repo-creds.yaml".
# apiVersion: v1
# kind: Secret
# metadata:
#   name: my-private-https-repo
#   namespace: argocd
#   labels:
#     argocd.argoproj.io/secret-type: repository
# stringData:
#   url: https://github.com/argoproj/argocd-example-apps
#   password: my-password
#   username: my-username
#   insecure: "true" # Ignore validity of server's TLS certificate. Defaults to "false"
#   forceHttpBasicAuth: "true" # Skip auth method negotiation and force usage of HTTP basic auth. Defaults to "false"
#   enableLfs: "true" # Enable git-lfs for this repository. Defaults to "false"
---
apiVersion: v1
kind: Secret
metadata:
  name: helmfileexamples-ssh-repo-access
  namespace: argo-cd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:mjhfvi/HelmfileExamples.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABCZf7L2T/
    QmIr4IAZw6M0hvAAAAGAAAAAEAAAAzAAAAC3NzaC1lZDI1NTE5AAAAIGeeOZFodxM/8Dak
    U4C63L4j1wA8SE8th25rcxg0WWTNAAAAwGooARK2kyT7rdewCVlG9RYgC5XYgBwkE67THE
    jhUnBFKTjFisLlZdI1BYUEG52iOWkg3sX/SZwyKzIoqdLZBluyb6okPrA+XveljgpPv0OQ
    1K5CZRYjRO5FaMDNU2ZxQRLgeYVbW6nN6s5cIMzmeUZU1fsthrU+zhmgGx61yE88A50S2F
    lO4CEFeoWP99pyWxSvLn0T3FMNgXBKA5EYNqp8UVSc1WIkQqgb05Dio8tAjnXnt9HXsFnN
    ZF8pgucfSA==
    -----END OPENSSH PRIVATE KEY-----
  insecure: "true"    # Do not perform a host key check for the server. Defaults to "false"
  enableLfs: "true"   # Enable git-lfs for this repository. Defaults to "false"

# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: istio-helm-repo
#   namespace: argocd
#   labels:
#     argocd.argoproj.io/secret-type: repository
# stringData:
#   url: https://storage.googleapis.com/istio-prerelease/daily-build/master-latest-daily/charts
#   name: istio.io
#   type: helm
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: private-helm-repo
#   namespace: argocd
#   labels:
#     argocd.argoproj.io/secret-type: repository
# stringData:
#   url: https://my-private-chart-repo.internal
#   name: private-repo
#   type: helm
#   password: my-password
#   username: my-username
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: private-repo
#   namespace: argocd
#   labels:
#     argocd.argoproj.io/secret-type: repository
# stringData:
#   url: https://github.com/argoproj/private-repo